language: cpp
dist: xenial
os: linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-multilib

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - make
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL


deploy:
  provider: releases
  api_key:
      secure: Q+VluK+TfVvX0AkVKleQevicAdJG59d2Rq17N1TGp6tojG/z5xpUVqOnUBVM7Pl8Wd7v0BN6UcxIsNe8PGX83ys/R8rN9KS4STR0ifDCFUOjBrduYKaI5k4QXoq9RTP4lgNZii83TcjBeKYoCzZ5XkP+HAcC0vVFuA+2T69V5PzfGMKNYoUQcioNVqwvnEtrFO77UcXt97Vd7Wm+XONgpUhaFCIyIk79+nhBn0zqQd8yRD9XZZkyYnJyiXrT0VN/d0A4Y0wnGEedZM8Wk2jozV9sfMq3RWba2j/0hL8HnFReC/NzFFgekKmIzYaMOK+YNjL61GyaqpA1Jl5sz/yocfA4y3jSR8x6ZGzqxcfJN7xt31oMXG2S1aonhyhK77J07ihawxzq3jgYKsBvg9eOCJgv8Iy89YxK1Y9rViUgVbnbHIgmfimHWvSXt2cOF/TIvtTLExaBRSPxVp3W2M68ewRMoEHCSwlFnMUpVxY8S4W5bvB7/VPV0QXx1dxJk8EWIl+jrLZmYX/fB+5Nzvvc3tXs+EYB1O2iU7aGtjrdzgx42pY263v2bE+ZFF2lk4mjqrGcHXaWR1axAZpPEAQ44SAVmFRuW5j17TbFlMF4dLQL2Gz1LpOYPTZyAfB+OkhdOjlQXH+mLEEsZ46CdhoqU6/2TfYjDr00O55KAz8jgBs=
  file: "test/plugins/cec.so"
  skip_cleanup: true
  on:
    tags: true