{
  "language": "cpp",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "compiler": [
    "gcc"
  ],
  "addons": {
    "apt": {
      "packages": [
        "g++-multilib"
      ]
    }
  },
  "before_script": [
    "mkdir build && cd build",
    "cmake .."
  ],
  "script": [
    "make",
    "cd .."
  ],
  "deploy": [
    {
      "provider": "bintray",
      "file": "bintray.json",
      "user": "aktah",
      "key": 
      {
        "secure": "Plt3Tv1PLKyOKRONpQ0RP71nvIC9rKF0LrzFQK1u/QZV21Qa7lfmEdHd1g06gqWqr5rUtrNQKnnJOS3fANPdXLfmkseKghXy/7ESN41r0VeODJU8zBP3TNnKGHv5S+Cvw74ddq6PsORZERasw+L4+xPJ89x4WhgSXqMZz0m2hjN2v6XfhwV0Zng6aOhhfqrAgnZzDxzgyhr55bHvG9rE0fgciRY1+xlfXdQV4KLqNh7VKuj73JMK6KEzwyNc8poD++rmlKJzIccWjQk1s1ZB3Ta22VSkAVMErzv9U+0GIBksiZzQBmls/G825Jtr27wP4xPZvm94UL4bkAlUBJV1s6DBXAyGdA4z7N0/IVaha82/UHv+dnL0+6ZkC1/z3X3wxQ0S+5iYq94OwOkbdpwVJQEy1VbbsCnqoB35zSB+Lk8bTORJdc9nE7jp7ttVljsGiFKmqt4gFJ98G5BvlhEtaEZ5DsD/OEokJHYrUsebXzrXSf7ErIfeMneNC/BIfNLC6o1ZmqUvVJB5tTEbzk+wObUzNgtlU42MJt2Xq7qWtW89N69L8duk7JPEQ6twiXA9BXe0kCeKMa3HeadKLzId2SjbefP+oqmhB8bwSXrfc4keEBf/pB1k/TbCo/dxg5Twtnv+xtrJaSC5paEV2Bg+6A3DwwOnR+tMQe1SJ3mi1PI="
      },
      "skip_cleanup": true
    }
  ]
}