language: cpp
dist: xenial
os: linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-multilib

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL


deploy:
  provider: releases
  api_key:
      secure: MlV8tLn+QnIPQp+O23Hu+wlgx9pqWcCjLjLAfHy08Fu14LHrFhA+h3SWuxlyu3kFj5Lz0D8Dh77j65w73akMkVBlnlpNPst/QA5SqCTLfsl9Zn48hHoTfMVULdOfKvNMOJAZd5szTCYPen9LIDsdDHLsHZWsamYtDaOI5wk6xDNy6F0Frmevx//+qGCvCLdqINS5lzEFp589ou/eNE3+G+XNDgJVA0y194bh45llMsT0o4YzrixztRpFIp0WkwHtSBqtU/S/DRjSzAorafyGBibzYb+waSgaZj4pRl7yJ5kJ24+LzacUDHgUSKWHQCjJP3nuqawsWbVmwnP8zCkQOQEdYGcsCEWJF6b5Z347pGA2h7z4C47zsCBfft6Gz4z2DY6lkMW+ko1dtpfUKy3C8wEn5gL57yXlQnRCiDp8b+cgasyfTN8QtZugbP4yR4dVj7Ow4Xi1Ldps8n+JQoWd7iisL5TKg4cCAC4VNXimCkJNs3IQTGliIpV+revh13KmxY9bTz56KYruUEmgEsdfxS1EhyzJHcW8qbuE9h7fkbThBFuBI+cZmDuolIvSPWhlA/VVd4bk/jZcn1wdfBSn465LiY7XJwBqNpTRFyKlB/z5Iyv3Q2vK8lNvny76LGiGHbQJi9So6s6IbgQ8ZUcGx65rPGYP7iGeegecjLPwZ1c=
  file: "test/plugins/cec.so"
  skip_cleanup: true
  on:
    tags: true
