{
  "language": "cpp",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "compiler": [
    "gcc"
  ],
  "addons": {
    "apt": {
      "packages": [
        "g++-multilib"
      ]
    }
  },
  "before_script": [
    "mkdir build && cd build",
    "cmake .."
  ],
  "script": [
    "make",
    "cd .."
  ],
  "deploy": [
    {
      "provider": "bintray",
      "file": "bintray.json",
      "user": "aktah",
      "key": 
      {
        "secure": "XI1Sk19WA8lZHvprzMmzgwPKi80dbQP9eSM8C6SO7SmpFKr71RkXcQP/aJmV1nsZNKeB+8ZICWDVUoOZqh7Ri2mk82RWm2481Imt243XpjUGKSJSsIGT+RGpGIfKcP97zjY/jpsl3nkZRYoFR8fPwL2y0i4fVu1b37eipCf5ibFA+uUDiO/LBbL2dyehmQX2SgCTn2uT6l5tHRR2XeiNDeJWk30CbFI7aHxtJetmIYzzK8+nrXsEmUQu7a1cT0DRTStJB8n6L6qsn2G4sUgUy5YezB4yP7468AA36lF92jE0rh4gQI2leSUMdrMhjouD/aoQ1WFVxfdbWLKzxJIhAZm+2m9XEBj+RIFDWg6RIu6lNJljvlv/f7TOR39L97LSbGYIDtSNKdax6XpbBdL8so9eaUJ4EBrAU+RZ+zDTxVO6GVsVSTiX/zq0Ej53E8TCLiTI8m0nalxiecBJk3e5qxw4WgUF3VMUZrieydgExcGpImyC+8COeE6G/7l1zX1eTbtTBd3Yqi3RYkRb7nX9G2G4zKY66/A6Ll+Kl95+2wpIK8ieRMrpMY6F311IV3xRrDWbpzcJl2yIL7CYXZE4aZL1vmIzLWpPwtk8h934y7P3TjbDJQrQ4/3SKyNjDH5eg2WcpDuq/m7ThQxiPmJcm7dLDkeZJNkJ7r6eVhxdAEA="
      },
      "skip_cleanup": true,
      "after_success": [
        "wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh",
        "chmod +x send.sh",
        "./send.sh success $WEBHOOK_URL"
      ],
      "after_failure": [
        "wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh",
        "chmod +x send.sh",
        "./send.sh failure $WEBHOOK_URL"
      ]
    }
  ]
}