language: cpp
dist: xenial
os: linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-multilib

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL


deploy:
  provider: releases
  api_key:
    secure: BYjtxQTw3RuDUYZJVem1HdkFcp62ykHhvSnGurqqOZ+LVZeKjHjTxxf8bWcPiUAQPnoR3E7CkEO1hPcA9ypj+Y1/TBCcZ/CxcLXdL9ecnBKQNI8K1b7kme93DqosxR883KJrsz49HimIS5FoYBmMrvqDXbLbQNwVhhIcyCTnEN97xN4pTQViJ+M1F9CjgBZLNb8T82kJ2+jQJiC8xhnYe3qj4bkgxtzb2bOIhdZ2WVVE7Lwlyy6JdSLnzegfg3gFDesXHaaJyq8i5xzA+MolyycPF09vhPQD3o0bTKb77T1ehsJr6Zy/fWOSb/TuA1aByPAgVNGMaOe0y62Lr4EnQ+TGJ0+JwOtLCtbEMuRbeGsd4tD/zDIQeXwwur2z6Hk1Z4+0xpNiZkJfK1jCMjtl2J1LUoZ75YAnYczdkx8g1TRWR62X3M83WCvyRs2oDq5e0kwsxPBkXnhJPQG3NZgQgZCm7CJvTeb/WrvB8OmXA0pW6wh2Exw7ym9GQu2xj5B7Qx4i9cEATIvxcu0LmZaK8eM4X4dJ/GYy0zpfUg7uAAbGmMo0bgOb0ZvClWNaAB9ziwh5vyLgt+eqmFD7v3mv1aTLKaIVuq2AU0D4UUDBd4SaT4zyD4ik5Iw+OcBcbjb7MXBn8IRM87chAC6VDqU19hOfkbGv6X2zQhGnnYdQr64=
  file: "test/plugins/cec.so"
  skip_cleanup: true
  on:
    tags: true
