language: cpp
dist: xenial
os: linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-multilib

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL


deploy:
  provider: releases
  api_key:
      secure: YAUzkHq4VRB7qb3bo3/0xk2ajP1vK1bTHJKXL4GGUx7+DOcFIrVuK+Iu8kA7Oc/DQI8ucERv8/PKaVSEiRdBOWazbOIzShvTAjp7XC0DzOnY+tlCfMoaIelMZPO6493jm+0O6Br7TabYHe7UIvJxSHFSAngUeFI6gCl0O3He9XenbAN6rWO1OmYg4KBkiASej3/PCGZ+S6mppeR9l8fhCSwuxltCYl18kDr3RkQ5kLlbPAvZh3u7/Xn4pLZ5aAOOV9Ng3g3yi/t3s0KSEevwxdF1wpbu5E8ejgXsP9gAne+5cdwuSzS9iz92PGXtUdUw5eIuZHZBKvLmPscjjKkTnIyHC7dhxqWFPGR8xPGcqRXHadYLmarkQ9VTJ/FF3RHuFy086wFLC50iPFJ4Dt9dtDGdhyelp5quyzleHQ8rfeEbve3seZaXdy3eVkzCrSh1nqsSwKR1+7OAvAfO1otpaF+nSgI+s+JCvZyTYAr9PwY7p7pISQaha1NgORsy8MUsbhjBUv++05KgTMVI5E0L0Q0ad8KCcNGZiVNXpFhVWbIfnbqM5rSGrP0De6Z72yEbg66Lf1/eEtgymZZliRmbV8p9E47jAULQn6NbQPmwVIt8TWq+Z5Z2wGulk0UIQpM1jEFJ0q2GVhlxBb7WINXlHgE+esLreTZ2Ex9QuM6lWCY=
  file: "test/plugins/cec.so"
  skip_cleanup: true
  on:
    tags: true
