version: "{build}"
image: 
  - Visual Studio 2015

configuration:
  - Release

install:
  - git submodule update --init --recursive .

before_build:
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 10 2010"

build_script:
  - cmake --build . --config %CONFIGURATION%

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

artifacts:
  - path: test/plugins/$(configuration)/cec.dll
    name: Plugin

  
deploy:
  release: v1.0-latest
  description: 'โค้ดล่าสุดจาก CEFix Repository'
  provider: GitHub
  auth_token:
    secure: j+0h0w3HGoF5ZEb3kCkz/i6Tknyak31ZiL10LMlFlFymoxzmssd7Gapy2VZg/WCC # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only